
package com.ibsplc.wsdl.ndc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NdcResService", targetNamespace = "http://www.ibsplc.com/wsdl/ndc", wsdlLocation = "http://demo.ibsplc.aero/iRes_NdcRes_WS/services/NdcResServiceSOAPPort?wsdl")
public class NdcResService
    extends Service
{

    private final static URL NDCRESSERVICE_WSDL_LOCATION;
    private final static WebServiceException NDCRESSERVICE_EXCEPTION;
    private final static QName NDCRESSERVICE_QNAME = new QName("http://www.ibsplc.com/wsdl/ndc", "NdcResService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://demo.ibsplc.aero/iRes_NdcRes_WS/services/NdcResServiceSOAPPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NDCRESSERVICE_WSDL_LOCATION = url;
        NDCRESSERVICE_EXCEPTION = e;
    }

    public NdcResService() {
        super(__getWsdlLocation(), NDCRESSERVICE_QNAME);
    }

    public NdcResService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NDCRESSERVICE_QNAME, features);
    }

    public NdcResService(URL wsdlLocation) {
        super(wsdlLocation, NDCRESSERVICE_QNAME);
    }

    public NdcResService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NDCRESSERVICE_QNAME, features);
    }

    public NdcResService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NdcResService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NdcResServicePort
     */
    @WebEndpoint(name = "NdcResServiceSOAPPort")
    public NdcResServicePort getNdcResServiceSOAPPort() {
        return super.getPort(new QName("http://www.ibsplc.com/wsdl/ndc", "NdcResServiceSOAPPort"), NdcResServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NdcResServicePort
     */
    @WebEndpoint(name = "NdcResServiceSOAPPort")
    public NdcResServicePort getNdcResServiceSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibsplc.com/wsdl/ndc", "NdcResServiceSOAPPort"), NdcResServicePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NDCRESSERVICE_EXCEPTION!= null) {
            throw NDCRESSERVICE_EXCEPTION;
        }
        return NDCRESSERVICE_WSDL_LOCATION;
    }

}
