
package com.ibsplc.wsdl.ndc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.iata.iata.edist.Acknowledgement;
import org.iata.iata.edist.AirDocDisplayRQ;
import org.iata.iata.edist.AirDocDisplayRS;
import org.iata.iata.edist.AirShoppingRQ;
import org.iata.iata.edist.AirShoppingRS;
import org.iata.iata.edist.BaggageAllowanceRQ;
import org.iata.iata.edist.BaggageAllowanceRS;
import org.iata.iata.edist.BaggageChargesRQ;
import org.iata.iata.edist.BaggageChargesRS;
import org.iata.iata.edist.BaggageListRQ;
import org.iata.iata.edist.BaggageListRS;
import org.iata.iata.edist.FareRulesRQ;
import org.iata.iata.edist.FareRulesRS;
import org.iata.iata.edist.FlightPriceRQ;
import org.iata.iata.edist.FlightPriceRS;
import org.iata.iata.edist.InvGuaranteeRQ;
import org.iata.iata.edist.InvGuaranteeRS;
import org.iata.iata.edist.InvReleaseNotif;
import org.iata.iata.edist.ItinReshopRQ;
import org.iata.iata.edist.ItinReshopRS;
import org.iata.iata.edist.OrderCancelRQ;
import org.iata.iata.edist.OrderCancelRS;
import org.iata.iata.edist.OrderChangeRQ;
import org.iata.iata.edist.OrderCreateRQ;
import org.iata.iata.edist.OrderListRQ;
import org.iata.iata.edist.OrderListRS;
import org.iata.iata.edist.OrderRetrieveRQ;
import org.iata.iata.edist.OrderViewRS;
import org.iata.iata.edist.SeatAvailabilityRQ;
import org.iata.iata.edist.SeatAvailabilityRS;
import org.iata.iata.edist.ServiceListRQ;
import org.iata.iata.edist.ServiceListRS;
import org.iata.iata.edist.ServicePriceRQ;
import org.iata.iata.edist.ServicePriceRS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NdcResServicePort", targetNamespace = "http://www.ibsplc.com/wsdl/ndc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.iata.iata.edist.ObjectFactory.class,
    com.ibsplc.iflyres.simpletypes.ObjectFactory.class
})
public interface NdcResServicePort {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.AirShoppingRS
     */
    @WebMethod(action = "shopAir")
    @WebResult(name = "AirShoppingRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public AirShoppingRS shopAir(
        @WebParam(name = "AirShoppingRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        AirShoppingRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.Acknowledgement
     */
    @WebMethod(action = "releaseInventory")
    @WebResult(name = "Acknowledgement", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public Acknowledgement releaseInventory(
        @WebParam(name = "InvReleaseNotif", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        InvReleaseNotif parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.InvGuaranteeRS
     */
    @WebMethod(action = "guaranteeInventory")
    @WebResult(name = "InvGuaranteeRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public InvGuaranteeRS guaranteeInventory(
        @WebParam(name = "InvGuaranteeRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        InvGuaranteeRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.OrderViewRS
     */
    @WebMethod(action = "createOrder")
    @WebResult(name = "OrderViewRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public OrderViewRS createOrder(
        @WebParam(name = "OrderCreateRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        OrderCreateRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.BaggageAllowanceRS
     */
    @WebMethod(action = "getBaggageAllowance")
    @WebResult(name = "BaggageAllowanceRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public BaggageAllowanceRS getBaggageAllowance(
        @WebParam(name = "BaggageAllowanceRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        BaggageAllowanceRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.ServiceListRS
     */
    @WebMethod(action = "listServices")
    @WebResult(name = "ServiceListRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public ServiceListRS listServices(
        @WebParam(name = "ServiceListRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        ServiceListRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.ServicePriceRS
     */
    @WebMethod(action = "priceServices")
    @WebResult(name = "ServicePriceRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public ServicePriceRS priceServices(
        @WebParam(name = "ServicePriceRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        ServicePriceRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.OrderViewRS
     */
    @WebMethod(action = "retrieveOrder")
    @WebResult(name = "OrderViewRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public OrderViewRS retrieveOrder(
        @WebParam(name = "OrderRetrieveRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        OrderRetrieveRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.FareRulesRS
     */
    @WebMethod(action = "fareRules")
    @WebResult(name = "FareRulesRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public FareRulesRS fareRules(
        @WebParam(name = "FareRulesRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        FareRulesRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.OrderListRS
     */
    @WebMethod(action = "listOrder")
    @WebResult(name = "OrderListRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public OrderListRS listOrder(
        @WebParam(name = "OrderListRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        OrderListRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.SeatAvailabilityRS
     */
    @WebMethod(action = "showSeatAvailability")
    @WebResult(name = "SeatAvailabilityRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public SeatAvailabilityRS showSeatAvailability(
        @WebParam(name = "SeatAvailabilityRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        SeatAvailabilityRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.AirDocDisplayRS
     */
    @WebMethod(action = "airDocDisplay")
    @WebResult(name = "AirDocDisplayRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public AirDocDisplayRS airDocDisplay(
        @WebParam(name = "AirDocDisplayRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        AirDocDisplayRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.BaggageListRS
     */
    @WebMethod(action = "getBaggageList")
    @WebResult(name = "BaggageListRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public BaggageListRS getBaggageList(
        @WebParam(name = "BaggageListRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        BaggageListRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.BaggageChargesRS
     */
    @WebMethod(action = "getBaggageCharge")
    @WebResult(name = "BaggageChargesRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public BaggageChargesRS getBaggageCharge(
        @WebParam(name = "BaggageChargesRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        BaggageChargesRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.FlightPriceRS
     */
    @WebMethod(action = "flightPrice")
    @WebResult(name = "FlightPriceRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public FlightPriceRS flightPrice(
        @WebParam(name = "FlightPriceRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        FlightPriceRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.ItinReshopRS
     */
    @WebMethod(action = "itinReshop")
    @WebResult(name = "ItinReshopRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public ItinReshopRS itinReshop(
        @WebParam(name = "ItinReshopRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        ItinReshopRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.OrderCancelRS
     */
    @WebMethod(action = "orderCancel")
    @WebResult(name = "OrderCancelRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public OrderCancelRS orderCancel(
        @WebParam(name = "OrderCancelRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        OrderCancelRQ parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns org.iata.iata.edist.OrderViewRS
     */
    @WebMethod(action = "orderChange")
    @WebResult(name = "OrderViewRS", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
    public OrderViewRS orderChange(
        @WebParam(name = "OrderChangeRQ", targetNamespace = "http://www.iata.org/IATA/EDIST", partName = "parameters")
        OrderChangeRQ parameters);

}
